<?php
$aMenuLinks = array(
    array(
        "Каталог",
        "/catalog/",
        array(),
        array(),
    ),
    array(
        "Коллекции",
        "/collections/",
        array(),
        array(),
    ),
    array(
        "Как заказать",
        "/order/",
        array(),
        array(),
    ),
    array(
        "О нас",
        "/about/",
        array(),
        array(),
    ),
    array(
        "Отзывы",
        "/reviews/",
        array(),
        array(),
    ),
    array(
        "Контакты",
        "/contacts/",
        array(),
        array(),
    ),
);
?>
